runtime: python37

handlers:
 - url: /api
   script: auto

 - url: /api/.*
   script: auto

 - url: /
   static_files: www/index.html
   upload: www/index.html

 - url: /(.*)
   static_files: www/\1
   upload: www/(.*)
